apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: eshop
  labels:
    app: user-service
  name: user-service
spec:
  ports:
  - port: 8012
    protocol: TCP
    targetPort: 8012
  selector:
    app: user-service
  type: NodePort
status:
  loadBalancer: {}
